#!/bin/bash

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

# Retrieve arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC
admin=$YNH_APP_ARG_ADMIN


#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Source YunoHost helpers
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

# store settings
ynh_app_setting_set $app is_public $is_public
ynh_app_setting_set $app admin $admin


#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

# Check or install docker
dockerapp_ynh_checkinstalldocker

# Check domain/path availability
dockerapp_ynh_loadvariables
ynh_webpath_available $domain $path_url
ynh_webpath_register $app $domain $path_url

#=================================================
# MODIFY A CONFIG FILE
#=================================================

admin_mail=$(ynh_user_get_info $admin 'mail')
ynh_replace_string "__PORT__" $port "docker/docker-compose.yml"
dockerapp_ynh_findreplaceallvaribles

secret_key=$(openssl rand -base64 64 | tr -d '\n')
ynh_replace_string "__YNH_KEY__" $secret_key "docker/_specificvariablesapp.sh"

#=================================================
# COPY CONF
#=================================================

# Copy files to the right place
dockerapp_ynh_copyconf

#=================================================
# START AND CREATE SERVICE
#=================================================

# docker run
dockerapp_ynh_run

docker exec docker_plausible_db_1 psql -U postgres -d plausible_db -c "UPDATE users SET email_verified = true;"

#=================================================
# NGINX CONFIGURATION
#=================================================

# Modify Nginx configuration file and copy it to Nginx conf directory
dockerapp_ynh_preparenginx

#=================================================
# SETUP SSOWAT
#=================================================


# Make app public if necessary or protect it
if [ $is_public -eq 1 ]
then
    ynh_app_setting_set $app skipped_uris "/"
fi


#=================================================
# RELOAD SSOWAT
#=================================================

# Regenerate SSOwat conf
dockerapp_ynh_reloadservices
