#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Source YunoHost helpers
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

# Retrieve app settings
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get "$app" domain)
path_url=$(ynh_app_setting_get "$app" path)
is_public=$(ynh_app_setting_get "$app" is_public)
admin=$(ynh_app_setting_get "$app" admin)
password=$(ynh_app_setting_get "$app" password)

admin_mail=$(ynh_user_get_info $admin 'mail')


dockerapp_ynh_loadvariables

#=================================================
# MODIFY A CONFIG FILE
#=================================================

admin_mail=$(ynh_user_get_info $admin 'mail')
ynh_replace_string "__PORT__" $port "docker/docker-compose.yml"

dockerapp_ynh_findreplaceallvaribles

secret_key=$(openssl rand -base64 64 | tr -d '\n')
ynh_replace_string "__YNH_KEY__" $secret_key "docker/_specificvariablesapp.sh"

#=================================================
# COPY CONF
#=================================================

# Copy files to the right place
dockerapp_ynh_copyconf

#=================================================
# STOP AND REMOVE SERVICE
#=================================================

# docker rm
dockerapp_ynh_rm

#=================================================
# START AND CREATE SERVICE
#=================================================

# docker run
dockerapp_ynh_run

#docker exec docker_plausible_db_1 psql -U postgres -d plausible_db -c "UPDATE users SET email_verified = true;"


#=================================================
# NGINX CONFIGURATION
#=================================================

# Modify Nginx configuration file and copy it to Nginx conf directory
dockerapp_ynh_preparenginx

#=================================================
# SETUP SSOWAT
#=================================================


# Make app public if necessary or protect it
if [ $is_public -eq 1 ]
then
    ynh_app_setting_set $app skipped_uris "/"
else
    ynh_app_setting_set $app protected_uris "/"
fi


#=================================================
# RELOAD SSOWAT
#=================================================

# Regenerate SSOwat conf
dockerapp_ynh_reloadservices
